/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StatsRouteImport } from './routes/stats'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as PostRouteImport } from './routes/post'
import { Route as MonitorRouteImport } from './routes/monitor'
import { Route as DraftRouteImport } from './routes/draft'
import { Route as IndexRouteImport } from './routes/index'
import { Route as IntegrationsSocialAddingRouteImport } from './routes/integrations/social/adding'
import { Route as IntegrationsSocialXIndexRouteImport } from './routes/integrations/social/x/index'
import { Route as IntegrationsSocialLinkedinIndexRouteImport } from './routes/integrations/social/linkedin/index'
import { Route as IntegrationsSocialXCallbackRouteImport } from './routes/integrations/social/x/callback'
import { Route as IntegrationsSocialLinkedinCallbackRouteImport } from './routes/integrations/social/linkedin/callback'

const StatsRoute = StatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const PostRoute = PostRouteImport.update({
  id: '/post',
  path: '/post',
  getParentRoute: () => rootRouteImport,
} as any)
const MonitorRoute = MonitorRouteImport.update({
  id: '/monitor',
  path: '/monitor',
  getParentRoute: () => rootRouteImport,
} as any)
const DraftRoute = DraftRouteImport.update({
  id: '/draft',
  path: '/draft',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationsSocialAddingRoute =
  IntegrationsSocialAddingRouteImport.update({
    id: '/integrations/social/adding',
    path: '/integrations/social/adding',
    getParentRoute: () => rootRouteImport,
  } as any)
const IntegrationsSocialXIndexRoute =
  IntegrationsSocialXIndexRouteImport.update({
    id: '/integrations/social/x/',
    path: '/integrations/social/x/',
    getParentRoute: () => rootRouteImport,
  } as any)
const IntegrationsSocialLinkedinIndexRoute =
  IntegrationsSocialLinkedinIndexRouteImport.update({
    id: '/integrations/social/linkedin/',
    path: '/integrations/social/linkedin/',
    getParentRoute: () => rootRouteImport,
  } as any)
const IntegrationsSocialXCallbackRoute =
  IntegrationsSocialXCallbackRouteImport.update({
    id: '/integrations/social/x/callback',
    path: '/integrations/social/x/callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const IntegrationsSocialLinkedinCallbackRoute =
  IntegrationsSocialLinkedinCallbackRouteImport.update({
    id: '/integrations/social/linkedin/callback',
    path: '/integrations/social/linkedin/callback',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/draft': typeof DraftRoute
  '/monitor': typeof MonitorRoute
  '/post': typeof PostRoute
  '/settings': typeof SettingsRoute
  '/setup': typeof SetupRoute
  '/stats': typeof StatsRoute
  '/integrations/social/adding': typeof IntegrationsSocialAddingRoute
  '/integrations/social/linkedin/callback': typeof IntegrationsSocialLinkedinCallbackRoute
  '/integrations/social/x/callback': typeof IntegrationsSocialXCallbackRoute
  '/integrations/social/linkedin/': typeof IntegrationsSocialLinkedinIndexRoute
  '/integrations/social/x/': typeof IntegrationsSocialXIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/draft': typeof DraftRoute
  '/monitor': typeof MonitorRoute
  '/post': typeof PostRoute
  '/settings': typeof SettingsRoute
  '/setup': typeof SetupRoute
  '/stats': typeof StatsRoute
  '/integrations/social/adding': typeof IntegrationsSocialAddingRoute
  '/integrations/social/linkedin/callback': typeof IntegrationsSocialLinkedinCallbackRoute
  '/integrations/social/x/callback': typeof IntegrationsSocialXCallbackRoute
  '/integrations/social/linkedin': typeof IntegrationsSocialLinkedinIndexRoute
  '/integrations/social/x': typeof IntegrationsSocialXIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/draft': typeof DraftRoute
  '/monitor': typeof MonitorRoute
  '/post': typeof PostRoute
  '/settings': typeof SettingsRoute
  '/setup': typeof SetupRoute
  '/stats': typeof StatsRoute
  '/integrations/social/adding': typeof IntegrationsSocialAddingRoute
  '/integrations/social/linkedin/callback': typeof IntegrationsSocialLinkedinCallbackRoute
  '/integrations/social/x/callback': typeof IntegrationsSocialXCallbackRoute
  '/integrations/social/linkedin/': typeof IntegrationsSocialLinkedinIndexRoute
  '/integrations/social/x/': typeof IntegrationsSocialXIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/draft'
    | '/monitor'
    | '/post'
    | '/settings'
    | '/setup'
    | '/stats'
    | '/integrations/social/adding'
    | '/integrations/social/linkedin/callback'
    | '/integrations/social/x/callback'
    | '/integrations/social/linkedin/'
    | '/integrations/social/x/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/draft'
    | '/monitor'
    | '/post'
    | '/settings'
    | '/setup'
    | '/stats'
    | '/integrations/social/adding'
    | '/integrations/social/linkedin/callback'
    | '/integrations/social/x/callback'
    | '/integrations/social/linkedin'
    | '/integrations/social/x'
  id:
    | '__root__'
    | '/'
    | '/draft'
    | '/monitor'
    | '/post'
    | '/settings'
    | '/setup'
    | '/stats'
    | '/integrations/social/adding'
    | '/integrations/social/linkedin/callback'
    | '/integrations/social/x/callback'
    | '/integrations/social/linkedin/'
    | '/integrations/social/x/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DraftRoute: typeof DraftRoute
  MonitorRoute: typeof MonitorRoute
  PostRoute: typeof PostRoute
  SettingsRoute: typeof SettingsRoute
  SetupRoute: typeof SetupRoute
  StatsRoute: typeof StatsRoute
  IntegrationsSocialAddingRoute: typeof IntegrationsSocialAddingRoute
  IntegrationsSocialLinkedinCallbackRoute: typeof IntegrationsSocialLinkedinCallbackRoute
  IntegrationsSocialXCallbackRoute: typeof IntegrationsSocialXCallbackRoute
  IntegrationsSocialLinkedinIndexRoute: typeof IntegrationsSocialLinkedinIndexRoute
  IntegrationsSocialXIndexRoute: typeof IntegrationsSocialXIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/stats': {
      id: '/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof StatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/post': {
      id: '/post'
      path: '/post'
      fullPath: '/post'
      preLoaderRoute: typeof PostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/monitor': {
      id: '/monitor'
      path: '/monitor'
      fullPath: '/monitor'
      preLoaderRoute: typeof MonitorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/draft': {
      id: '/draft'
      path: '/draft'
      fullPath: '/draft'
      preLoaderRoute: typeof DraftRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integrations/social/adding': {
      id: '/integrations/social/adding'
      path: '/integrations/social/adding'
      fullPath: '/integrations/social/adding'
      preLoaderRoute: typeof IntegrationsSocialAddingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integrations/social/x/': {
      id: '/integrations/social/x/'
      path: '/integrations/social/x'
      fullPath: '/integrations/social/x/'
      preLoaderRoute: typeof IntegrationsSocialXIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integrations/social/linkedin/': {
      id: '/integrations/social/linkedin/'
      path: '/integrations/social/linkedin'
      fullPath: '/integrations/social/linkedin/'
      preLoaderRoute: typeof IntegrationsSocialLinkedinIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integrations/social/x/callback': {
      id: '/integrations/social/x/callback'
      path: '/integrations/social/x/callback'
      fullPath: '/integrations/social/x/callback'
      preLoaderRoute: typeof IntegrationsSocialXCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integrations/social/linkedin/callback': {
      id: '/integrations/social/linkedin/callback'
      path: '/integrations/social/linkedin/callback'
      fullPath: '/integrations/social/linkedin/callback'
      preLoaderRoute: typeof IntegrationsSocialLinkedinCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DraftRoute: DraftRoute,
  MonitorRoute: MonitorRoute,
  PostRoute: PostRoute,
  SettingsRoute: SettingsRoute,
  SetupRoute: SetupRoute,
  StatsRoute: StatsRoute,
  IntegrationsSocialAddingRoute: IntegrationsSocialAddingRoute,
  IntegrationsSocialLinkedinCallbackRoute:
    IntegrationsSocialLinkedinCallbackRoute,
  IntegrationsSocialXCallbackRoute: IntegrationsSocialXCallbackRoute,
  IntegrationsSocialLinkedinIndexRoute: IntegrationsSocialLinkedinIndexRoute,
  IntegrationsSocialXIndexRoute: IntegrationsSocialXIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
